export const CATEGORY_PLACE_TYPES = {
    food: [
        "restaurant",
        "fast_food_restaurant",
        "pizza_restaurant",
        "sandwich_shop",
        "diner",
        "food_court",
        "breakfast_restaurant",
        "brunch_restaurant",
        "buffet_restaurant",
        "hamburger_restaurant",
        "japanese_restaurant",
        "korean_restaurant",
        "italian_restaurant",
        "mexican_restaurant",
        "chinese_restaurant",
        "seafood_restaurant",
        "steak_house",
        "sushi_restaurant",
        "ramen_restaurant",
        "american_restaurant",
        "filipino_restaurant",
        "asian_restaurant",
        "barbecue_restaurant",
        "bistro",
        "meal_takeaway",
    ],
    coffee: [
        "coffee_shop",
        "cafe",
        "coffee_stand",
        "coffee_roastery",
        "tea_house",
        "tea_store",
        "cat_cafe",
        "dog_cafe",
        "cafeteria",
    ],
    dessert: [
        "dessert_shop",
        "dessert_restaurant",
        "ice_cream_shop",
        "bakery",
        "pastry_shop",
        "donut_shop",
        "candy_store",
        "chocolate_shop",
        "confectionery",
        "cake_shop",
        "acai_shop",
    ],
    drinks: [
        "cocktail_bar",
        "wine_bar",
        "lounge_bar",
        "brewery",
        "brewpub",
        "pub",
        "bar",
        "beer_garden",
        "juice_shop",
        "tea_house",
        "winery",
        "bar_and_grill",
    ],
    bars: [
        "bar",
        "pub",
        "sports_bar",
        "cocktail_bar",
        "lounge_bar",
        "night_club",
        "beer_garden",
        "irish_pub",
        "brewpub",
        "hookah_bar",
    ],
    entertainment: [
        "amusement_center",
        "amusement_park",
        "movie_theater",
        "bowling_alley",
        "video_arcade",
        "comedy_club",
        "live_music_venue",
        "concert_hall",
        "event_venue",
        "karaoke",
        "go_karting_venue",
        "miniature_golf_course",
        "performing_arts_theater",
        "tourist_attraction",
        "indoor_playground",
        "water_park",
        "casino",
    ],
    shopping: [
        "shopping_mall",
        "department_store",
        "clothing_store",
        "market",
        "book_store",
        "gift_shop",
        "shoe_store",
        "jewelry_store",
        "thrift_store",
        "womens_clothing_store",
        "sporting_goods_store",
        "flea_market",
        "store",
    ],
    parks: [
        "park",
        "city_park",
        "botanical_garden",
        "garden",
        "picnic_ground",
        "dog_park",
        "national_park",
        "nature_preserve",
        "hiking_area",
    ],
    karaoke: [
        "karaoke",
    ],
    sports: [
        "gym",
        "fitness_center",
        "sports_club",
        "sports_complex",
        "sports_activity_location",
        "bowling_alley",
        "swimming_pool",
        "tennis_court",
        "golf_course",
        "indoor_golf_course",
        "adventure_sports_center",
        "arena",
        "stadium",
        "athletic_field",
        "ice_skating_rink",
    ],
    wellness: [
        "spa",
        "massage_spa",
        "massage",
        "wellness_center",
        "sauna",
        "yoga_studio",
        "skin_care_clinic",
        "beauty_salon",
        "foot_care",
    ],
} as const;


